---
name: _build

on:
  workflow_call:
    inputs:
      ruby_version:
        description: The Ruby version.
        type: string
        required: false
        default: '3.0.1'
    outputs:
      artifact_name:
        description: The artifact name.
        value: build-${{ github.sha }}

jobs:
  build:
    name: Gem
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          ruby_version: ${{ inputs.ruby_version }}
      - name: Build
        run: bundle exec rake build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.sha }}
          if-no-files-found: error
          path: pkg/
